### PR TITLE
Adding support for .coop domains

### PR DESCRIPTION
**Pull request by mxroo**
Adding support for .coop domains of the form Expiry Date: 14 Jan 2016 22:40:29 UTC

### CODE REVIEW

**Comment by glensc** [comment]
you should not create pull requests from master branch. i will have to cherry pick, because don't want extra merge commits that you have pushed here!

**Comment by glensc** [comment]
also, please include test tomain!

**Comment by mxroo** [comment]
Apologies for the mistakes, this is only my second github pull request.
What would be the best next step?

The domain I'm using to test is my own, palantetech.coop.

Thanks,

**Comment by glensc** [comment]
as you shared it publicly already, i'll include that in test suite :)

**Comment by glensc** [comment]
you should reset your 'master'  to be without your local changes:

```
git fetch https://github.com/glensc/nagios-plugin-check_domain.git
git checkout master
git reset --hard FETCH_HEAD
```

after then you can do next PR's normally, as the contributing instructions suggest:
https://github.com/glensc/nagios-plugin-check_domain#pull-requests

**Comment by mxroo** [comment]
Perfect. Thanks!

**Pull request closed without merging**
