### PR TITLE
Fix incorrect variable name of output file.

### PR DESCRIPTION
**Pull request by oasys**

### CODE REVIEW

**Comment by glensc** [comment]
cherry picked as e434ad6 and 5c28f51 and restored `set -e`, did not like it being removed

**Comment by glensc** [comment]
also, do you have sample domain (to be added to tests) what gets rate limited?

**Comment by oasys** [comment]
This won't work correctly, as 'set -e' will prevent you from ever being able to test $?.

The motivation for this patch is that the server that my whois client uses for .org lookups has a low rate-limit (about 5/10s?).  The client exits with a non-zero value, causing the script to exit (because of 'set -e') without the opportunity to return an error message to nagios.

I'm by no means an expert bash programmer, but it seem that 'set -e' is commonly discouraged in favor of more robust error checking.  This seemed like a better way to go.

I considered something like 'whois ... || die ...' which will bypass the 'set -e' checking for that command and allow for a better (general) error message, but that doesn't give the opportunity to parse the output for more specific errors (such as the rate-limit checking in this case).

Here's a test that shows the issue on my Debian wheezy system:
```
$ whois pir.org -s whois.pir.org
Warning: RIPE flags used with a traditional server.
WHOIS LIMIT EXCEEDED - SEE WWW.PIR.ORG/WHOIS FOR DETAILS
fgets: Connection reset by peer
$ echo $?
2
$ whois --version
Version 5.1.1.
$ ./check_domain.sh -d pir.org # with set -e
fgets: Connection reset by peer
```

**Comment by glensc** [comment]
did you test with recent version, i.e the one i committed? what's your `/bin/sh`? as here such construct works:

```
$ printf '#!/bin/sh\necho >&2 err\necho out\nexit 2' > fake
$ chmod +x fake 
$ ./check_domain.sh -P ./fake -d blah
err
UNKNOWN - WHOIS exited with error 2.
```

**Comment by oasys** [comment]
Sorry.  If had just read the code, rather than reacting to your "cherry picked" comment, I would've seen your ```&& error=$? || error=$?``` addition.  Works as expected.  Thanks!

**Comment by glensc** [comment]
yes. i cherry picked both, but amended the second commit

**Pull request closed without merging**
